services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - '5050:5050'
#services:
#  #POSTGRESQL
#  postgres-service:
#    image: postgres:14
#    container_name: postgres-service
#    restart: on-failure
#    env_file: ./.env
#    environment:
#      - 'POSTGRES_USER=$POSTGRES_USERNAME'
#      - 'POSTGRES_PASSWORD=$POSTGRES_PASSWORD'
#      - 'POSTGRES_DB=$POSTGRES_DATABASE'
#    ports:
#      - "5432:5432"
#    networks:
#      - my-network
#    expose:
#      - "5432"
#    volumes:
#      - db:/var/lib/postgres
#
##  #PGADMIN
##  pgadmin:
##    image: dpage/pgadmin4:latest
##    container_name: pg-admin
##    environment:
##      PGADMIN_DEFAULT_EMAIL: jost@tansu.com
##      PGADMIN_DEFAULT_PASSWORD: pass
##    ports:
##      - "5050:5050"
#
##  #SPRING BOOT APP
##  app:
##    container_name: app
##    image: spring/demo
##    build: ./
##    restart: on-failure
##    env_file: ./.env
##    ports:
##      - "8080:8089"
##    expose:
##      - "8089"
##    volumes:
##      - .m2:/root/.m2
##    networks:
##      - my-network
##    depends_on:
##      - postgres-service
#
#
#networks:
#  my-network:
#    driver: bridge
#
#volumes:
#  db:
