version: "3.8"

services:
  postgres-service:
    image: postgres:14rc1-alpine
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_SQL_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_SQL_PASSWORD
      - POSTGRES_DB=$POSTGRES_SQL_DATABASE
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      - postgres-service
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - "8080:8089"
    environment:
        "spring.datasource.url"  : jdbc:postgresql://postgres-service:$POSTGRES_SQL_DOCKER_PORT/$POSTGRES_SQL_DATABASE,
        "spring.datasource.username" : $POSTGRES_SQL_USERNAME,
        "spring.datasource.password" : $POSTGRES_SQL_PASSWORD,
        "spring.jpa.properties.hibernate.dialect" : org.hibernate.dialect.PostgreSQLDialect,
        "spring.jpa.hibernate.ddl-auto" : "update"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: