version: "3.8"

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_SQL_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_SQL_PASSWORD
      - POSTGRES_DB=$POSTGRES_SQL_DATABASE
    ports:
      - "8080:8089"
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      - postgresdb
    build: ./test-client
    restart: on-failure
    env_file: ./.env
    ports:
      - "8080:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgresdb:$POSTGRES_SQL_DOCKER_PORT/$POSTGRES_SQL_DATABASE",
        "spring.datasource.username" : "$POSTGRES_SQL_USERNAME",
        "spring.datasource.password" : "$POSTGRES_SQL_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: