version: "3.8"

services:
  #POSTGRESQL
  postgres-service:
    image: postgres:latest
    container_name: postgres-service
    restart: on-failure
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_SQL_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_SQL_PASSWORD
      - POSTGRES_DB=$POSTGRES_SQL_DATABASE
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - my-network
    volumes:
      - db:/var/lib/postgres

  #PGADMIN
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: jost@tansu.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - "5050:5050"

  #SPRING BOOT APP
  app:
    depends_on:
      - postgres-service
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - "8080:8089"
    expose:
      - "8089"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - my-network


networks:
  my-network:
    driver: bridge

volumes:
  db:
