spring:
#PROFILS
  profiles:
    active: ${ACTIVE_PROFILE:prod}

logging:
  level:
    root: INFO

  #PROBLEM DETAILS
  mvc:
    problemdetails:
      enabled: true


#SWAGGER
tansu:
  openapi:
    dev-url: http://localhost:${SERVER_PORT:8080}
    prod-url: http://tansu-api:8090



#SERVER WEB
server:
  port: ${SERVER_PORT:8080}


#MANAGEMENT ACTUATOR
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'




