#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: pass22#{#[
POSTGRES_SQL_DATABASE: prod
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432




#Server
SERVER_PORT: 8089
ACTIVE_PROFILE: prod