spring:
  datasource:
    url: jdbc:mysql://localhost:3306/proddb
    username: root
    password: jost@1
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

logging:
  level:
    root: INFO


#Server
SERVER_PORT: 8090
ACTIVE_PROFILE: prod

