spring:
  #DATASOURCE
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: jost
    password: pass
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

#Server
SERVER_PORT: 8080
ACTIVE_PROFILE: dev
